/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.myspringboot;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.scheduling.annotation.EnableScheduling;
import org.springframework.web.client.RestTemplate;

@SpringBootApplication
@EnableScheduling
// ensures that a background task executor is created. Without it, nothing gets scheduled.
public class SpringBootBatchApp {

    public static void main(String[] args) {
        SpringApplication.run(SpringBootBatchApp.class, args);
    }
    
    @Bean
    public RestTemplate getRestTemplate() {
    	return new RestTemplate();
    }

}
