
openweatherapi:
  apikey: 64125ebb02bb7fd24ad526fe90e8827c
  apiparam: '&APPID=${openweatherapi.apikey}'
  basicuri: http://api.openweathermap.org/data/2.5/weather?q=
  responsemodehtml: '&mode=html'
  responseunitmetric: '&units=metric'
  responseunitFahrenheit: 'units=imperial'
  
server:
  port: 5000
#  servlet:
#    context-path: /${spring.application.name}
    

hometown:
     location: Khagaria
     emailaddresses: nice.neeraj09@gmail.com,nitishsingh356@gmail.com

weather-report-schedule:
         cronexpression: 0 30 0,7,13 ? * *
   
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: null
    url: jdbc:h2:file:./data/info/infodb
    username: user
   
   
  application:
    name: rest-info-service
          
  seconddatasource:
    driverClassName: org.h2.Driver
    password: null
    url: jdbc:h2:file:./data/info/detailinfo
    username: user 
           
  h2:
    console:
      enabled: true
      path: /h2-console
      
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
  mail:
        host: smtp.gmail.com
        username: sonusngh335@gmail.com
        password: Maillog@168
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    connectiontimeout: 5000
                    timeout: 5000
                    writetimeout: 5000

                    starttls:
                            enable: true  

        
       
rest-info-service:
  users: appuser,appadmin
  passwords: appuserpass,appadminpass
  
service:
     localeService:
            basicUri: http://REST-UTIL-SERVICE/application/getLocale/{attributename}

eureka:
  client:
    enabled: false
 
       
management:
     endpoint:
         info:
             enabled: true
         port: 9090
         
logging: 
   file:
     name: WeatherRestServiceApplicationLogs.txt       

