server:
     port: 8089
     servlet:      context-path: /dataloader-batch

spring:
  application:
    name: dataloader-batch
  batch:
    job:
      enabled: false
  h2:
    console:
      enabled: true
  jpa:    hibernate:      ddl-auto: update
         
  datasource:
              url: jdbc:h2:file:./data/data3
              driverClassName: org.h2.Driver
              username: sa
              password: null
   
input:
  filename: persons.csv
  
dataloaderbatch:
         stepname: FILELOADER
         jobname: DATALOADER
         cronexpression: 0 57-58 16 * * ?

app: 
 cronexpression: 0 15 16 * * ?
 otpchars: 1023456789
 defaultotplength: 4 
 defaultpasswordlength: 8
 passwordstring: aAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ
 
logging:
  level:
    root: info
    com.myspringboot: info
    com.myspringboot.provider.implementation: info
        

 
     

